org: maneveil
service: blogging-platform-api

provider:
  name: aws
  runtime: python3.13
  stage: dev
  environment:
    POSTS_TABLE_NAME: posts_${sls:stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:BatchWriteItem
          Resource:
            - "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.POSTS_TABLE_NAME}"
            - "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.POSTS_TABLE_NAME}/index/*"

resources:
 Resources:
  PostsDynamoDbTable:
    Type: 'AWS::DynamoDB::Table'
    DeletionPolicy: Retain
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:provider.environment.POSTS_TABLE_NAME}

functions:
  createPost:
    handler: handlers/posts.create
    memorySize: 512
    events:
      - httpApi:
          method: POST
          path: /posts
  getAllPosts:
    handler: handlers/posts.get_all
    memorySize: 512
    events:
      - httpApi:
          method: GET
          path: /posts
  getOnePost:
    handler: handlers/posts.get_one
    memorySize: 512
    events:
      - httpApi:
          method: GET
          path: /posts/{id}
  updatePost:
    handler: handlers/posts.update
    memorySize: 512
    events:
      - httpApi:
          method: PUT
          path: /posts/{id}
  deletePost:
    handler: handlers/posts.delete
    memorySize: 512
    events:
      - httpApi:
          method: DELETE
          path: /posts/{id}

custom:
  pythonRequirements:
    slim: true
    strip: true
    noDeploy:
      - boto3
      - botocore
      - docutils
      - jmespath
      - s3transfer

package:
  individually: true

plugins:
  - serverless-offline
